export const PROMOTORES_DADOS = [
    { id: 39, nome: "ALEXANDRE FREITAS DA SILVA", cidade: "" },
    { id: 37, nome: "JHONATTA WISNNER GONÇALVES", cidade: "" },
    { id: 65, nome: "ANDERSON WILLIAMS SANTOS TORRES", cidade: "PISTÃO SUL" },
    { id: 1, nome: "CARLOS DA GUIA NUNES", cidade: "GAMA E NOVO GAMA" },
    { id: 54, nome: "PAULO VICTOR RODRIGUES DE ALMEIDA", cidade: "SOBRADINHO" },
    { id: 2, nome: "ANTONIA AMANDA SIEBRA BATISTA", cidade: "PLANALTINA GOIAS E DF" },
    { id: 8, nome: "GRAZIELE MELO SILVA ALVES", cidade: "CEILANDIA E AGUAS CLARAS" },
    { id: 3, nome: "FRANCISCO PEREIRA MASCIMO", cidade: "AGUAS LINDAS / 070" },
    { id: 4, nome: "SAMILLE APARECIDA DOS SANTOS DAMASCENO BARBOSA", cidade: "EPTG / AGUAS / GUARA" },
    { id: 63, nome: "WYNGLEY SOARES CABRAL", cidade: "ASA NORTE / JARDIM BOTANICO" },
    { id: 45, nome: "MARIA EDUARDA CARDOSO DOS SANTOS", cidade: "" },
    { id: 12, nome: "GUILHERME RODRIGUES SILVA DE LIMA", cidade: "VICENTE PIRES / TATICO DA CEILANDIA / TAGUATINGA" },
    { id: 7, nome: "FRANKLIN MATOS RODRIGUES", cidade: "VALPARAISO / LUZIANIA" },
    { id: 44, nome: "PRISCYLLA GOMES DA SILVA", cidade: "SAMAMBAIA/ RIACHO / RECANTO" },
    { id: 38, nome: "LUCAS MATHEUS MOREIRA SILVA", cidade: "GOIANIA" },
    { id: 17, nome: "JONAS DUARTE DA SILVA", cidade: "GOIANIA" },
    { id: 24, nome: "BRENNO FELIPE GOMES DA SILVA", cidade: "GOIANIA" },
    { id: 18, nome: "MARCIO JERONIMO ALVES", cidade: "GOIANIA" },
    { id: 19, nome: "ROGERIO PEREIRA BARBOSA", cidade: "TRINDADE" },
    { id: 126, nome: "GABRIEL TERRA ANDRADE PORTELLA", cidade: "GOIANIA" },
    { id: 15, nome: "FRANCISCO JOSE DOS SANTOS LOURENÇO", cidade: "GOIANIA" },
    { id: 36, nome: "NUBIA FLAVIA LEITE", cidade: "GOIANIA" },
    { id: 23, nome: "FABIO CAMARGO DOS SANTOS", cidade: "GOIANIA" },
    { id: 29, nome: "SIMONE DE JESUS PEREIRA", cidade: "CATALAO" },
    { id: 55, nome: "THAYZA DE OLIVEIRA PEREIRA", cidade: "RIO VERDE" },
    { id: 25, nome: "MATHEUS RIBEIRO SILVA", cidade: "ITUMBIARA" },
    { id: 16, nome: "YAGO BORGES DE QUEIROZ", cidade: "ANAPOLIS" },
    { id: 22, nome: "MARCELO AUGUSTO DE OLIVEIRA PEREIRA GOMES", cidade: "" },
    { id: 26, nome: "RODRIGO MARQUES DE OLIVEIRA", cidade: "ANAPOLIS" },
    { id: 21, nome: "CAMILA TRINDADE DE OLIVEIRA", cidade: "JATAI" },
    { id: 28, nome: "LUCAS PEREIRA DE FARIA SILVA", cidade: "CALDAS NOVAS" },
    { id: 723, nome: "DANIEL ALEXANDRE DE ALMEIDA", cidade: "GOIÂNIA" },
    { id: 60, nome: "KAYQUE DE JESUS OLIVEIRA", cidade: "GOIANIA" },
    { id: 30, nome: "FERNANDA KELLY ALVES DA SILVA", cidade: "ARAGUAINA" },
    { id: 31, nome: "KEVEN ALBERTO PAULINO DE SOUSA", cidade: "PALMAS" },
    { id: 50, nome: "RAFAELA SILVA GOMES", cidade: "BARRA DO GARÇAS" },
    { id: 34, nome: "JEFFERSON JUNIOR DE SOUZA", cidade: "PRIMAVERA DO LESTE" },
    { id: 64, nome: "ERIK MATHEUS DE SOUZA MENDES", cidade: "SINOP" },
    { id: 62, nome: "ROSILENE DA SILVA GONCALVES GAMBARRA", cidade: "CUIABA/VÁRZEA GRANDE" },
    { id: 61, nome: "ALINE DA SILVA PROCOPIO", cidade: "DOURADOS" },
    { id: 33, nome: "ANA LETICIA ORTIZ AVALO", cidade: "CAMPO GRANDE" },
    { id: 6, nome: "MILLENA CONCEICAO MOURA CRUZ", cidade: "LUIS EDUARDO MAGALHAES" },
    { id: null, nome: "THALLYSON WILLIAM DE SOUSA SILVA", cidade: "" },
];

export const INDUSTRIAS = [
    "ALLEZA",
    "ÁPYCE",
    "AUTENTICOCO",
    "AO QUADRADO",
    "BANANA CORRENTE",
    "BOMPACK",
    "BUFALÍSSIMA",
    "BOMPACK-EMPÓRIO PRIME",
    "COPRA",
    "CICOPAL GO",
    "CO LATICÍNIOS",
    "COOPATOS",
    "FLORESTAL",
    "FRUTA POLPA",
    "GRUPO AMA",
    "IMAGINA",
    "RB ALIMENTOS",
    "KING",
    "MANTIQUEIRA",
    "MEDFIO",
    "MENDEZ",
    "MISSIATO",
    "PAMPLONA",
    "PACHA ALIMENTOS",
    "PIRACANJUBA",
    "SÃO BRAZ",
    "SELETA",
    "TERMOLAR",
    "VERDE CAMPO",
];

export const TODAS_LOJAS = [
    { rede: "DIA A DIA", loja: "DIA A DIA - LUÍS EDUARDO MAGALHÃES", uf: "BA" },
    { rede: "ATACADÃO", loja: "ATACADÃO - ASA NORTE", uf: "DF" },
    { rede: "ATACADÃO", loja: "ATACADÃO - BRASILIA", uf: "DF" },
    { rede: "ATACADÃO", loja: "ATACADÃO - BRASÍLIA SIA", uf: "DF" },
    { rede: "ATACADÃO", loja: "ATACADÃO - GAMA", uf: "DF" },
    { rede: "ATACADÃO", loja: "ATACADÃO - PISTÃO SUL 343", uf: "DF" },
    { rede: "ATACADÃO", loja: "ATACADÃO - RECANTO DAS EMAS", uf: "DF" },
    { rede: "ATACADÃO", loja: "ATACADÃO - SOBRADINHO", uf: "DF" },
    { rede: "ATACADÃO", loja: "ATACADÃO - TAGUATINGA QNL", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - 211 NORTE", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - 402 NORTE", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - 408 NORTE", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - 413 SUL", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - 508 SUL", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - CA 01", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - CASTANHEIRAS", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - CLSW QD 105", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - QI 05/08", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - QI 09/10", uf: "DF" },
    { rede: "BIG BOX", loja: "BIG BOX - ÁGUAS CLARAS (PAINEIRAS)", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPER - PARK SHOPPING", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - ASA NORTE", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - ASA NORTE II", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - ASA NORTE IV", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - ASA SUL I", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - ASA SUL II", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - BOM MOTIVO", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - GUARÁ", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - LAGO SUL", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - PARK SHOPPING", uf: "DF" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - ÁGUAS CLARAS", uf: "DF" },
    { rede: "COMPER", loja: "COMPER - ASA SUL LOJA 137", uf: "DF" },
    { rede: "COMPER", loja: "COMPER - GAMA LOJA 152", uf: "DF" },
    { rede: "COMPER", loja: "COMPER - PLANALTINA LOJA 187", uf: "DF" },
    { rede: "COMPER", loja: "COMPER - SOBRADINHO LOJA 157", uf: "DF" },
    { rede: "COMPER", loja: "COMPER - ÁGUAS CLARAS", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - ADE/EPNB ÁGUAS CLARAS", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - EPTG VICENTE PIRES", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - SENADOR CANEDO (DF)", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - TAGUATINGA NORTE", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - TAQUARI", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - TAQUARI (LAGO NORTE)", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - UNIEURO", uf: "DF" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - UNIEURO (AGUAS CLARAS)", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - 070", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - AGUAS CLARAS", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - CEILANDIA CENTRO", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - CEILANDIA SUL", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - EPTG", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - ESTÂNCIA MESTRE D'ARMAS", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - GAMA", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - JARDIM BOTÂNICO", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - MESTRE D'ARMAS", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - PISTÃO SUL", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - PLANALTINA DF", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - RECANTO DAS EMAS", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - RIACHO FUNDO", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - RIACHO FUNDO I", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - SAMAMBAIA", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - SAMAMBAIA 060", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - SAMAMBAIA FURNAS", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - SIA", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - SOBRADINHO", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - TAGUATINGA", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - VICENTE PIRES R 04", uf: "DF" },
    { rede: "DIA A DIA", loja: "DIA A DIA - VICENTE PIRES R 12", uf: "DF" },
    { rede: "EMPORIO PRIME", loja: "EMPORIO PRIME - BRASILIA", uf: "DF" },
    { rede: "FORT ATACADISTA", loja: "FORT ATACADISTA - CEILÂNDIA", uf: "DF" },
    { rede: "FORT ATACADISTA", loja: "FORT ATACADISTA - RECANTO DAS EMAS", uf: "DF" },
    { rede: "FORT ATACADISTA", loja: "FORT ATACADISTA - SOL NASCENTE", uf: "DF" },
    { rede: "FORT ATACADISTA", loja: "FORT ATACADISTA - TAGUATINGA", uf: "DF" },
    { rede: "PEROLA", loja: "PEROLA CALIXTOPOLIS", uf: "DF" },
    { rede: "PÃO", loja: "PÃO DE AÇÚCAR - GUARÁ II", uf: "DF" },
    { rede: "RIO VERMELHO", loja: "RIO VERMELHO MARACANÃ", uf: "DF" },
    { rede: "SUPER ADEGA", loja: "SUPER ADEGA - GAMA", uf: "DF" },
    { rede: "SUPER ADEGA", loja: "SUPER ADEGA - GUARA II", uf: "DF" },
    { rede: "SUPER ADEGA", loja: "SUPER ADEGA - JARDIM BOTÂNICO", uf: "DF" },
    { rede: "SUPER ADEGA", loja: "SUPER ADEGA - SIA", uf: "DF" },
    { rede: "SUPER ADEGA", loja: "SUPER ADEGA - TAGUATINGA NORTE", uf: "DF" },
    { rede: "SUPER ADEGA", loja: "SUPER ADEGA - TAGUATINGA SUL", uf: "DF" },
    { rede: "TATICO", loja: "TATICO - CEILANDIA SUL", uf: "DF" },
    { rede: "TATICO", loja: "TATICO - EPTG", uf: "DF" },
    { rede: "TATICO", loja: "TATICO - RECANTO DAS EMAS", uf: "DF" },
    { rede: "TATICO", loja: "TATICO - SAMAMBAIA NORTE", uf: "DF" },
    { rede: "TATICO", loja: "TATICO - SAMAMBAIA SUL", uf: "DF" },
    { rede: "TATICO", loja: "TATICO - SANTA MARIA", uf: "DF" },
    { rede: "TATICO", loja: "TATICO - VICENTE PIRES RUA 12", uf: "DF" },
    { rede: "ULTRABOX", loja: "ULTRABOX - EPTG", uf: "DF" },
    { rede: "ASSAÍ", loja: "ASSAÍ - ANÁPOLIS", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - CALDAS NOVAS", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - GOIÂNIA BURITIS", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - GOIÂNIA PERIMETRAL", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - GOIÂNIA PORTUGAL", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - GOIÂNIA T9", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - INDEPENDÊNCIA", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - RIO VERDE", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - VALPARAÍSO", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - ANAPOLIS", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - APARECIDA DE GOIANIA", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - APARECIDA DE GOIANIA AV. RIO VERDE", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - AV. INDEPENDÊNCIA", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - COSTA MADRI", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - FORMOSA", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - GOIANIA", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - GOIANIA FLAMBOYANT 717", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - GOIÁS NORTE 64 (JARDIM GOIÁS)", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - ITUMBIARA", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - RIO VERDE", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - ROD. DOS ROMEIROS 214", uf: "GO" },
    { rede: "ATACADÃO", loja: "ATACADÃO - VALPARAÍSO DE GOIÁS", uf: "GO" },
    { rede: "BRETAS", loja: "BRETAS - CATALÃO", uf: "GO" },
    { rede: "BRETAS", loja: "BRETAS - JATAI", uf: "GO" },
    { rede: "CAMPEÃO", loja: "CAMPEÃO SUPERMERCADO - SETOR DAS MANSÕES", uf: "GO" },
    { rede: "CAMPEÃO", loja: "CAMPEÃO SUPERMERCADO - VILA SANTA MARIA", uf: "GO" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - ANÁPOLIS", uf: "GO" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - AVENIDA T9", uf: "GO" },
    { rede: "CARREFOUR", loja: "CARREFOUR HIPERMERCADO - GOIANIA SUL JARDINS", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - AV. GOIÁS", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - JARDIM GOIAS (FLAMBOYANT)", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - LUZIANIA", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - MANSÕES ROSAS", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - PARQUE DAS LARANJEIRAS", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - PEDRO LUDOVICO (T-63)", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - RIO VERDE", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - SENADOR CANEDO", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - SETOR TRÊS MARIAS (MADRI)", uf: "GO" },
    { rede: "COSTA ATACADÃO", loja: "COSTA ATACADÃO - VALPARAÍSO DE GOIÁS", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - AGUAS LINDAS", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - CALDAS NOVAS", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - FORMOSA", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - GOIANÉSIA", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - ITUMBIARA", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - LUZIANIA", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - NOVO GAMA", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - PLANALTINA GO", uf: "GO" },
    { rede: "DIA A DIA", loja: "DIA A DIA - SANTO ANTONIO DO DESCOBERTO", uf: "GO" },
    { rede: "EMPORIO PRIME", loja: "EMPORIO PRIME - GOIANIA", uf: "GO" },
    { rede: "EMPORIO PRIME", loja: "EMPORIO PRIME - GOIANIA FLAMBOYANT", uf: "GO" },
    { rede: "EMPORIO PRIME", loja: "EMPORIO PRIME 85", uf: "GO" },
    { rede: "EMPORIO PRIME", loja: "EMPORIO PRIME ALPHAVILLE", uf: "GO" },
    { rede: "EMPORIO PRIME", loja: "EMPORIO PRIME JAMEL CECILIO", uf: "GO" },
    { rede: "FORT ATACADISTA", loja: "FORT ATACADISTA - VALPARAISO", uf: "GO" },
    { rede: "REDE MAX", loja: "REDE MAX - AV MUTIRÃO", uf: "GO" },
    { rede: "REDE MAX", loja: "REDE MAX - INDEPENDÊNCIA", uf: "GO" },
    { rede: "REDE MAX", loja: "REDE MAX - JARDIM BOA ESPERANÇA", uf: "GO" },
    { rede: "REDE MAX", loja: "REDE MAX - PARK REAL", uf: "GO" },
    { rede: "REDE MAX", loja: "REDE MAX - RIO VERDE", uf: "GO" },
    { rede: "REDE MAX", loja: "REDE MAX-TREMENDAO", uf: "GO" },
    { rede: "REDE MAX", loja: "REDE MAX-TRIUNFO", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 01", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 03", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 04", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 08", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 09", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 10", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 11", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 12", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 13", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 14", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 15", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 17", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 20", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 21", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 22", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 23", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 24", uf: "GO" },
    { rede: "REIS SUPERMERCADOS", loja: "REIS SUPERMERCADOS LOJA 25", uf: "GO" },
    { rede: "RIO VERMELHO", loja: "RIO VERMELHO - CATALÃO", uf: "GO" },
    { rede: "RIO VERMELHO", loja: "RIO VERMELHO - JUNDIAÍ", uf: "GO" },
    { rede: "RIO VERMELHO", loja: "RIO VERMELHO - MARACANÃ", uf: "GO" },
    { rede: "RIO VERMELHO", loja: "RIO VERMELHO - PECUARIA", uf: "GO" },
    { rede: "STORE", loja: "STORE - CAMPINAS", uf: "GO" },
    { rede: "STORE", loja: "STORE - CIDADE LIVRE", uf: "GO" },
    { rede: "STORE", loja: "STORE - FAMA", uf: "GO" },
    { rede: "STORE", loja: "STORE - MANSÕES PARAÍSO", uf: "GO" },
    { rede: "STORE", loja: "STORE - PERIMETRAL NORTE", uf: "GO" },
    { rede: "STORE", loja: "STORE - SERRINHA", uf: "GO" },
    { rede: "STORE", loja: "STORE - TRINDADE CENTRO", uf: "GO" },
    { rede: "STORE", loja: "STORE - URIAS MAGALHÃES", uf: "GO" },
    { rede: "STORE", loja: "STORE - VILA MORAIS", uf: "GO" },
    { rede: "SUPER ADEGA", loja: "SUPER ADEGA - VALPARAÍSO", uf: "GO" },
    { rede: "SUPERMERCADO FLORESTA", loja: "SUPERMERCADO FLORESTA - MARACANÃ", uf: "GO" },
    { rede: "SUPERMERCADO FLORESTA", loja: "SUPERMERCADO FLORESTA - PARQUE BRASILIA 2A ETAPA", uf: "GO" },
    { rede: "SUPERMERCADO FLORESTA", loja: "SUPERMERCADO FLORESTA - SETOR CENTRAL", uf: "GO" },
    { rede: "SUPERMERCADOS BRASIL", loja: "SUPERMERCADOS BRASIL 1 - SANTA LUZIA", uf: "GO" },
    { rede: "SUPERMERCADOS BRASIL", loja: "SUPERMERCADOS BRASIL 2 - CENTRO", uf: "GO" },
    { rede: "SUPERMERCADOS BRASIL", loja: "SUPERMERCADOS BRASIL 3 - SÃO CRISTÓVÃO", uf: "GO" },
    { rede: "SUPERMERCADOS BRASIL", loja: "SUPERMERCADOS BRASIL 4 NOVA AURORA - CENTRO", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - ALEXANDRINA LOJA 11", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - BAIRRO ITATIAIA LOJA 01", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - BAIRRO J.K LOJA 12", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - BAIRRO JAIARA - LOJA 09", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - BAIRRO JAIARA LOJA 03", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - BAIRRO S. JORGE LOJA 08", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - CENTRO", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - CENTRO LOJA 04", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - CIDADE JARDIM", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - JARDIM AMÉRICA LOJA 07", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - JARDIM DAS OLIVEIRAS 14 (SENADOR CANEDO)", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - LOJA 06 RECANTO DO SOL", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI - SENADOR CANEDO", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI SUPERMERCADOS - JARDIM GOIANO", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI SUPERMERCADOS - PRESIDENTE KENNEDY", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI SUPERMERCADOS - RES. DAS FLORES", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI SUPERMERCADOS - SANTA MARIA DE NAZARETH", uf: "GO" },
    { rede: "SUPERVI", loja: "SUPERVI SUPERMERCADOS - VILA JAIARA", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - AGUAS LINDAS LOJA 01", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - AGUAS LINDAS LOJA 02", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - CAMPINAS", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - CAPUAVA", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - CENTRAL", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - GARAVELO", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - JD AMÉRICA", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - OESTE", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - PAPILON", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - PORTAL SHOPPING", uf: "GO" },
    { rede: "TATICO", loja: "TATICO - T7", uf: "GO" },
    { rede: "ULTRABOX", loja: "ULTRABOX - PLANALTINA GO", uf: "GO" },
    { rede: "VILLEFORT", loja: "VILLEFORT - ANÁPOLIS", uf: "GO" },
    { rede: "VILLEFORT", loja: "VILLEFORT - JATAÍ", uf: "GO" },
    { rede: "ASSAÍ", loja: "ASSAÍ - ACRISUL", uf: "MS" },
    { rede: "ASSAÍ", loja: "ASSAÍ - CAMPO GRANDE AEROPORTO", uf: "MS" },
    { rede: "ASSAÍ", loja: "ASSAÍ - CENTENÁRIO", uf: "MS" },
    { rede: "ASSAÍ", loja: "ASSAÍ - CORONEL ANTONINO", uf: "MS" },
    { rede: "ASSAÍ", loja: "ASSAÍ - DOURADOS", uf: "MS" },
    { rede: "ASSAÍ", loja: "ASSAÍ - GUNTER HANS", uf: "MS" },
    { rede: "ASSAÍ", loja: "ASSAÍ - JOAQUIM MURTINHO", uf: "MS" },
    { rede: "ASSAÍ", loja: "ASSAÍ - PALMAS TEOTÔNIO 01", uf: "TO" },
];

export const DIAS = ["SEG", "TER", "QUA", "QUI", "SEX", "SAB", "DOM"];
export const DIAS_LABELS = {
    SEG: "Segunda",
    TER: "Terça",
    QUA: "Quarta",
    QUI: "Quinta",
    SEX: "Sexta",
    SAB: "Sábado",
    DOM: "Domingo",
};
export const UF_CORES = { DF: "#3b82f6", GO: "#8b5cf6", MT: "#06b6d4", MS: "#10b981", TO: "#f59e0b", BA: "#ec4899" };
export const ROTEIROS_INICIAIS = [
    {
        id: 1,
        industria: "ALLEZA",
        loja: "ATACADÃO - APARECIDA DE GOIANIA",
        uf: "GO",
        promotor: "MARCELO AUGUSTO DE OLIVEIRA PEREIRA GOMES",
        dias: { SEG: true, TER: true, QUA: true, QUI: true, SEX: true, SAB: true, DOM: true },
        supervisor: "LUCAS",
    },
    {
        id: 2,
        industria: "ALLEZA",
        loja: "ASSAI - TAGUATINGA SHOPPING",
        uf: "DF",
        promotor: "JHONATTA WISNNER GONÇALVES",
        dias: { SEG: true, TER: true, QUA: true, QUI: true, SEX: true, SAB: true, DOM: true },
        supervisor: "ALEXANDRE",
    },
];
